### ISSUE TITLE
What does the program actually do?

### ISSUE THREAD

**Issue by shroudUnwalked** [asusguy94/Porn-Organizer#3]
The readme explains extensively how to set up. But it is not clear to me what your porn-organizer does or will do. Is it supposed to be a file browser? Or does it classify porn on its own?

**Comment by asusguy94** [comment]
It is an organization system. It automatically imports files from the videos folder and applies the date and star information, any other tags/bookmarks etc. has to be added manually.

Stars-page has a parser that can fetch information from freeones.com, or you can add information manually. The parser will never override existing information.

So a file-browser would be the closest comparison
